name: Update badges

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:
          CREDLY_USER: lamtruong
          CREDLY_SORT: RECENT
          BADGE_SIZE: 110
